In [1]:
#Importing Data
import csv
import pandas as pd

with open('grade.csv', 'r') as file:
    reader = csv.DictReader(file)
    original_data = list(reader)

print("Original Dataset:\n")
print("StudentID\tName\t\tMarks")
for row in original_data:
    print(f"{row['StudentID']}\t\t{row['Name']}\t\t{row['Marks']}")



#Mapper Function
def mapper(data):
    mapped_data = []
    for row in data:
        student_id = row['StudentID']
        name = row['Name']
        marks = int(row['Marks'])
        mapped_data.append((student_id, name, marks))
    return mapped_data



#Reducer function
def reducer(mapped_data):
    reduced_data = []
    for student_id, name, marks in mapped_data:
        if marks >= 90:
            grade = 'A'
        elif marks >= 80:
            grade = 'B'
        elif marks >= 70:
            grade = 'C'
        elif marks >= 60:
            grade = 'D'
        else:
            grade = 'F'
        reduced_data.append((student_id, name, marks, grade))
    return reduced_data




#Output the result
mapped = mapper(original_data)
reduced = reducer(mapped)

print("\nDataset with Grades:\n")
print("StudentID\tName\t\tMarks\tGrade")
for student_id, name, marks, grade in reduced:
    print(f"{student_id}\t\t{name}\t\t{marks}\t{grade}")

Original Dataset:

StudentID	Name		Marks
101		John		85
102		Alice		92
103		Bob		76
104		Carol		58
105		David		67
106		Emma		89
107		Ryan		45
108		Sophia		95
109		Michael		72
110		Olivia		83
111		Ethan		61
112		Ava		78
113		James		88
114		Mia		54
115		Daniel		69
116		Harper		91
117		Henry		73
118		Ella		66
119		Lucas		80
120		Grace		59

Dataset with Grades:

StudentID	Name		Marks	Grade
101		John		85	B
102		Alice		92	A
103		Bob		76	C
104		Carol		58	F
105		David		67	D
106		Emma		89	B
107		Ryan		45	F
108		Sophia		95	A
109		Michael		72	C
110		Olivia		83	B
111		Ethan		61	D
112		Ava		78	C
113		James		88	B
114		Mia		54	F
115		Daniel		69	D
116		Harper		91	A
117		Henry		73	C
118		Ella		66	D
119		Lucas		80	B
120		Grace		59	F